Account pages
books4u-tcc/frontend pull request #5
Opened 2024-05-13 23:19 UTC by RodBerw

2024-05-13 23:24 UTC, lvolks approved these changes

2024-05-13 23:31 UTC, metehus requested changes

2024-05-13 23:31 UTC, metehus commented on src/router/router.tsx
> +    path: '/account',
seria `/account` mesmo?
acho que podemos deixar `/account` para a página da conta
e `/account/register` para essa de cadastro

2024-05-13 23:33 UTC, RodBerw commented on src/router/router.tsx
> +    path: '/account',
Ent tem que ver, já que seria a mesma página, também dava pra passar por props qual elemento é mostrado (cadastro ou login)

2024-05-14 17:36 UTC, metehus commented on src/router/router.tsx
> +    path: '/account',
pode ser `/account/access` ou `/account/signin` então

2024-05-24 02:01 UTC, metehus approved these changes

2024-05-24 02:02 UTC, merged