Login page
books4u-tcc/frontend pull request #6
Opened 2024-05-24 15:35 UTC by RodBerw

2024-05-24 16:59 UTC, metehus approved these changes

2024-05-24 17:00 UTC, metehus requested changes

2024-05-24 17:00 UTC, metehus commented on src/components/account/login.tsx
> +            <Text fontSize="2xl" mb={4}>Criar conta</Text>
```suggestion
            <Text fontSize="2xl" mb={4}>Entrar</Text>
```

2024-05-24 17:00 UTC, metehus commented on src/components/account/login.tsx
> +                <Button type="submit" colorScheme="blue" mt={4}>Registrar</Button>
```suggestion
                <Button type="submit" colorScheme="blue" mt={4}>Entrar</Button>
```

2024-05-26 01:13 UTC, lvolks approved these changes

2024-05-26 19:25 UTC, metehus approved these changes

2024-05-26 19:25 UTC, merged